apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swagger-api
  template:
    metadata:
      labels:
        app: swagger-api
    spec:
      containers:
        - name: swagger-api
          image: dockerrcs2024anac/swagger-api:latest
          ports:
            - containerPort: 3000
